### ISSUE TITLE
usr/sys time is binary

### ISSUE THREAD

**Issue by brendangregg** [uber-common/cpustat#1]
In fancy mode (which really is fancy!) the usr/sys plot only has points for 0 and 1k:

![screen shot 2016-03-03 at 2 37 59 pm](https://cloud.githubusercontent.com/assets/1101211/13512115/b07bc520-e14d-11e5-8d4c-1345593fd855.png)

BTW, I love the color selection in the comm and pid columns.

**Comment by mranney** [comment]
That's very strange. How did you run it? Also, what was the computer doing besides cpustat?

**Comment by brendangregg** [comment]
oh, I had run:

```
./cpustat -i=1 -t=true
```

Dropping the -i=1 makes it work.

I had added it since a plain ```./cpustat``` wasn't doing anything without it. I'd assumed the help message was wrong and -i was actually in seconds, not ms. But I guess -i is for the -t mode.

So what does -i mean without -t?:

```
# time ./cpustat -i=1000
^Cquitting on signal

real	0m22.664s
user	0m0.291s
sys	0m0.285s
```

that's 22 seconds without any output.

**Comment by mranney** [comment]
I have since update the README to explain the args and changed the defaults. If you refresh your copy, you should see that default of -i=200 and -s=10. 

-i=1 sets the sample interval to 1ms. I can only imagine what sort of edge cases this triggers, because there's more than 1ms of work to do. I guess I should put a lower bound on the sample size and also track if we are trying to sample faster than is possible.

**Comment by brendangregg** [comment]
I'll close this ticket (user error).
